package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotAftersale;
import com.yunqiic.iot.db.domain.IotAftersaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotAftersaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    long countByExample(IotAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    int deleteByExample(IotAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    int insert(IotAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    int insertSelective(IotAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    IotAftersale selectOneByExample(IotAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    IotAftersale selectOneByExampleSelective(@Param("example") IotAftersaleExample example, @Param("selective") IotAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    List<IotAftersale> selectByExampleSelective(@Param("example") IotAftersaleExample example, @Param("selective") IotAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    List<IotAftersale> selectByExample(IotAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    IotAftersale selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    IotAftersale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    IotAftersale selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotAftersale record, @Param("example") IotAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotAftersale record, @Param("example") IotAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}