package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotAddress;
import com.yunqiic.iot.db.domain.IotAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    long countByExample(IotAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    int deleteByExample(IotAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    int insert(IotAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    int insertSelective(IotAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    IotAddress selectOneByExample(IotAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    IotAddress selectOneByExampleSelective(@Param("example") IotAddressExample example, @Param("selective") IotAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    List<IotAddress> selectByExampleSelective(@Param("example") IotAddressExample example, @Param("selective") IotAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    List<IotAddress> selectByExample(IotAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    IotAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    IotAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    IotAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotAddress record, @Param("example") IotAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotAddress record, @Param("example") IotAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_address
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}