package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotBrand;
import com.yunqiic.iot.db.domain.IotBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    long countByExample(IotBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    int deleteByExample(IotBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    int insert(IotBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    int insertSelective(IotBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    IotBrand selectOneByExample(IotBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    IotBrand selectOneByExampleSelective(@Param("example") IotBrandExample example, @Param("selective") IotBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    List<IotBrand> selectByExampleSelective(@Param("example") IotBrandExample example, @Param("selective") IotBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    List<IotBrand> selectByExample(IotBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    IotBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    IotBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    IotBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotBrand record, @Param("example") IotBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotBrand record, @Param("example") IotBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}