package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotCoupon;
import com.yunqiic.iot.db.domain.IotCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    long countByExample(IotCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(IotCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    int insert(IotCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    int insertSelective(IotCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    IotCoupon selectOneByExample(IotCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    IotCoupon selectOneByExampleSelective(@Param("example") IotCouponExample example, @Param("selective") IotCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    List<IotCoupon> selectByExampleSelective(@Param("example") IotCouponExample example, @Param("selective") IotCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    List<IotCoupon> selectByExample(IotCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    IotCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    IotCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    IotCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotCoupon record, @Param("example") IotCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotCoupon record, @Param("example") IotCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}