package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotCategory;
import com.yunqiic.iot.db.domain.IotCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    long countByExample(IotCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    int deleteByExample(IotCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    int insert(IotCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    int insertSelective(IotCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    IotCategory selectOneByExample(IotCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    IotCategory selectOneByExampleSelective(@Param("example") IotCategoryExample example, @Param("selective") IotCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    List<IotCategory> selectByExampleSelective(@Param("example") IotCategoryExample example, @Param("selective") IotCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    List<IotCategory> selectByExample(IotCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    IotCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    IotCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    IotCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotCategory record, @Param("example") IotCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotCategory record, @Param("example") IotCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}