package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotCouponUser;
import com.yunqiic.iot.db.domain.IotCouponUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(IotCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(IotCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    int insert(IotCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(IotCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    IotCouponUser selectOneByExample(IotCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    IotCouponUser selectOneByExampleSelective(@Param("example") IotCouponUserExample example, @Param("selective") IotCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    List<IotCouponUser> selectByExampleSelective(@Param("example") IotCouponUserExample example, @Param("selective") IotCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    List<IotCouponUser> selectByExample(IotCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    IotCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    IotCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    IotCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotCouponUser record, @Param("example") IotCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotCouponUser record, @Param("example") IotCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}