package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotCart;
import com.yunqiic.iot.db.domain.IotCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    long countByExample(IotCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    int deleteByExample(IotCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    int insert(IotCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    int insertSelective(IotCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    IotCart selectOneByExample(IotCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    IotCart selectOneByExampleSelective(@Param("example") IotCartExample example, @Param("selective") IotCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    List<IotCart> selectByExampleSelective(@Param("example") IotCartExample example, @Param("selective") IotCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    List<IotCart> selectByExample(IotCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    IotCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    IotCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    IotCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotCart record, @Param("example") IotCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotCart record, @Param("example") IotCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}