package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotGoodsAttribute;
import com.yunqiic.iot.db.domain.IotGoodsAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(IotGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(IotGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    int insert(IotGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(IotGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    IotGoodsAttribute selectOneByExample(IotGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    IotGoodsAttribute selectOneByExampleSelective(@Param("example") IotGoodsAttributeExample example, @Param("selective") IotGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    List<IotGoodsAttribute> selectByExampleSelective(@Param("example") IotGoodsAttributeExample example, @Param("selective") IotGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    List<IotGoodsAttribute> selectByExample(IotGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    IotGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    IotGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    IotGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotGoodsAttribute record, @Param("example") IotGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotGoodsAttribute record, @Param("example") IotGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}