package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotGoods;
import com.yunqiic.iot.db.domain.IotGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    long countByExample(IotGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    int deleteByExample(IotGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    int insert(IotGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    int insertSelective(IotGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    IotGoods selectOneByExample(IotGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    IotGoods selectOneByExampleSelective(@Param("example") IotGoodsExample example, @Param("selective") IotGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    IotGoods selectOneByExampleWithBLOBs(IotGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    List<IotGoods> selectByExampleSelective(@Param("example") IotGoodsExample example, @Param("selective") IotGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    List<IotGoods> selectByExampleWithBLOBs(IotGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    List<IotGoods> selectByExample(IotGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    IotGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    IotGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    IotGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotGoods record, @Param("example") IotGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") IotGoods record, @Param("example") IotGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotGoods record, @Param("example") IotGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(IotGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}