package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotGoodsProduct;
import com.yunqiic.iot.db.domain.IotGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    long countByExample(IotGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(IotGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    int insert(IotGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(IotGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    IotGoodsProduct selectOneByExample(IotGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    IotGoodsProduct selectOneByExampleSelective(@Param("example") IotGoodsProductExample example, @Param("selective") IotGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    List<IotGoodsProduct> selectByExampleSelective(@Param("example") IotGoodsProductExample example, @Param("selective") IotGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    List<IotGoodsProduct> selectByExample(IotGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    IotGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    IotGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    IotGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotGoodsProduct record, @Param("example") IotGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotGoodsProduct record, @Param("example") IotGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}