package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotLog;
import com.yunqiic.iot.db.domain.IotLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    long countByExample(IotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    int deleteByExample(IotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    int insert(IotLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    int insertSelective(IotLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    IotLog selectOneByExample(IotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    IotLog selectOneByExampleSelective(@Param("example") IotLogExample example, @Param("selective") IotLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    List<IotLog> selectByExampleSelective(@Param("example") IotLogExample example, @Param("selective") IotLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    List<IotLog> selectByExample(IotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    IotLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    IotLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    IotLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotLog record, @Param("example") IotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotLog record, @Param("example") IotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}