package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotNotice;
import com.yunqiic.iot.db.domain.IotNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    long countByExample(IotNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    int deleteByExample(IotNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    int insert(IotNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    int insertSelective(IotNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    IotNotice selectOneByExample(IotNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    IotNotice selectOneByExampleSelective(@Param("example") IotNoticeExample example, @Param("selective") IotNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    List<IotNotice> selectByExampleSelective(@Param("example") IotNoticeExample example, @Param("selective") IotNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    List<IotNotice> selectByExample(IotNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    IotNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    IotNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    IotNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotNotice record, @Param("example") IotNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotNotice record, @Param("example") IotNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}