package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotNoticeAdmin;
import com.yunqiic.iot.db.domain.IotNoticeAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotNoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    long countByExample(IotNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    int deleteByExample(IotNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    int insert(IotNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    int insertSelective(IotNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    IotNoticeAdmin selectOneByExample(IotNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    IotNoticeAdmin selectOneByExampleSelective(@Param("example") IotNoticeAdminExample example, @Param("selective") IotNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    List<IotNoticeAdmin> selectByExampleSelective(@Param("example") IotNoticeAdminExample example, @Param("selective") IotNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    List<IotNoticeAdmin> selectByExample(IotNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    IotNoticeAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    IotNoticeAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    IotNoticeAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotNoticeAdmin record, @Param("example") IotNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotNoticeAdmin record, @Param("example") IotNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}