package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotOrderGoods;
import com.yunqiic.iot.db.domain.IotOrderGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    long countByExample(IotOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(IotOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    int insert(IotOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(IotOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    IotOrderGoods selectOneByExample(IotOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    IotOrderGoods selectOneByExampleSelective(@Param("example") IotOrderGoodsExample example, @Param("selective") IotOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    List<IotOrderGoods> selectByExampleSelective(@Param("example") IotOrderGoodsExample example, @Param("selective") IotOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    List<IotOrderGoods> selectByExample(IotOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    IotOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    IotOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    IotOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotOrderGoods record, @Param("example") IotOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotOrderGoods record, @Param("example") IotOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}