package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotOrder;
import com.yunqiic.iot.db.domain.IotOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    long countByExample(IotOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    int deleteByExample(IotOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    int insert(IotOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    int insertSelective(IotOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    IotOrder selectOneByExample(IotOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    IotOrder selectOneByExampleSelective(@Param("example") IotOrderExample example, @Param("selective") IotOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    List<IotOrder> selectByExampleSelective(@Param("example") IotOrderExample example, @Param("selective") IotOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    List<IotOrder> selectByExample(IotOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    IotOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    IotOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    IotOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotOrder record, @Param("example") IotOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotOrder record, @Param("example") IotOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}