package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotRole;
import com.yunqiic.iot.db.domain.IotRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    long countByExample(IotRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    int deleteByExample(IotRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    int insert(IotRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    int insertSelective(IotRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    IotRole selectOneByExample(IotRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    IotRole selectOneByExampleSelective(@Param("example") IotRoleExample example, @Param("selective") IotRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    List<IotRole> selectByExampleSelective(@Param("example") IotRoleExample example, @Param("selective") IotRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    List<IotRole> selectByExample(IotRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    IotRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    IotRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    IotRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotRole record, @Param("example") IotRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotRole record, @Param("example") IotRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}