package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotSearchHistory;
import com.yunqiic.iot.db.domain.IotSearchHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    long countByExample(IotSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    int deleteByExample(IotSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    int insert(IotSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    int insertSelective(IotSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    IotSearchHistory selectOneByExample(IotSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    IotSearchHistory selectOneByExampleSelective(@Param("example") IotSearchHistoryExample example, @Param("selective") IotSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    List<IotSearchHistory> selectByExampleSelective(@Param("example") IotSearchHistoryExample example, @Param("selective") IotSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    List<IotSearchHistory> selectByExample(IotSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    IotSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    IotSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    IotSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotSearchHistory record, @Param("example") IotSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotSearchHistory record, @Param("example") IotSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}