package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotSystem;
import com.yunqiic.iot.db.domain.IotSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    long countByExample(IotSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    int deleteByExample(IotSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    int insert(IotSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    int insertSelective(IotSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    IotSystem selectOneByExample(IotSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    IotSystem selectOneByExampleSelective(@Param("example") IotSystemExample example, @Param("selective") IotSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    List<IotSystem> selectByExampleSelective(@Param("example") IotSystemExample example, @Param("selective") IotSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    List<IotSystem> selectByExample(IotSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    IotSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    IotSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    IotSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotSystem record, @Param("example") IotSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotSystem record, @Param("example") IotSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}