package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotStorage;
import com.yunqiic.iot.db.domain.IotStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    long countByExample(IotStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    int deleteByExample(IotStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    int insert(IotStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    int insertSelective(IotStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    IotStorage selectOneByExample(IotStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    IotStorage selectOneByExampleSelective(@Param("example") IotStorageExample example, @Param("selective") IotStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    List<IotStorage> selectByExampleSelective(@Param("example") IotStorageExample example, @Param("selective") IotStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    List<IotStorage> selectByExample(IotStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    IotStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    IotStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    IotStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotStorage record, @Param("example") IotStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotStorage record, @Param("example") IotStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}