package com.yunqiic.iot.db.dao;

import com.yunqiic.iot.db.domain.IotTopic;
import com.yunqiic.iot.db.domain.IotTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IotTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    long countByExample(IotTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    int deleteByExample(IotTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    int insert(IotTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    int insertSelective(IotTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    IotTopic selectOneByExample(IotTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    IotTopic selectOneByExampleSelective(@Param("example") IotTopicExample example, @Param("selective") IotTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    IotTopic selectOneByExampleWithBLOBs(IotTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    List<IotTopic> selectByExampleSelective(@Param("example") IotTopicExample example, @Param("selective") IotTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    List<IotTopic> selectByExampleWithBLOBs(IotTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    List<IotTopic> selectByExample(IotTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    IotTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IotTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    IotTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    IotTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IotTopic record, @Param("example") IotTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") IotTopic record, @Param("example") IotTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IotTopic record, @Param("example") IotTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IotTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(IotTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IotTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") IotTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iot_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}